Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2019-06, with the labels that each got.

#223 9-regular-expressions/12-regexp-anchors
  9-regular-expressions/12-regexp-anchors/1-start-end/solution.md
  9-regular-expressions/12-regexp-anchors/1-start-end/task.md
  9-regular-expressions/12-regexp-anchors/2-test-mac/solution.md
  9-regular-expressions/12-regexp-anchors/2-test-mac/task.md
  9-regular-expressions/12-regexp-anchors/article.md
Labels: needs +1, review needed

#218 Translation of Microtasks and event loop
  1-js/11-async/07-microtask-queue/article.md
Labels: needs +1, review needed

#209 Перевод Focusing: focus/blur
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/my.css
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/source.view/my.css
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/task.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/bagua.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/my.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/script.js
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/bagua.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/my.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/source.view/script.js
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
  2-ui/4-forms-controls/2-focus-blur/article.md
Labels: ready to merge, review needed

#206 wip(2-ui/2-events/04-default-browser-action): Перевести главу
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.view/index.html
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/source.view/index.html
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.view/index.html
  2-ui/2-events/04-default-browser-action/3-image-gallery/source.view/index.html
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/2-events/04-default-browser-action/article.md
Labels: ready to merge, review needed

#152 Translate 1-js/02-first-steps/16-javascript-specials/
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: partially reviewed, ready to merge, review needed

#203 7-animations/1-bezier-curve
  7-animation/1-bezier-curve/article.md
  7-animation/index.md
Labels: ready to merge, review needed

#208 Scripts: async, defer
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/02-script-async-defer/long.js
  2-ui/5-loading/02-script-async-defer/small.js
Labels: ready to merge, review needed

#137 перевод /1-js/06-advanced-functions/06-function-object/
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/_js.view/source.js
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/solution.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
  1-js/06-advanced-functions/06-function-object/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
Labels: ready to merge, review needed

#190 Перевод Dom navigation
  2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
  2-ui/1-document/03-dom-navigation/1-dom-children/task.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/solution.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/task.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/solution.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/source.view/index.html
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md
  2-ui/1-document/03-dom-navigation/article.md
Labels: ready to merge, review needed

#185 Attributes and properties
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: ready to merge, review needed

#86 Translated /1-js/06-advanced-functions/02-rest-parameters-spread-operator
  1-js/06-advanced-functions/02-rest-parameters-spread-operator/article.md
Labels: needs +1, review needed

#224 Scrolling
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.view/index.html
  2-ui/3-event-details/8-onscroll/1-endless-page/source.view/index.html
  2-ui/3-event-details/8-onscroll/1-endless-page/task.md
  2-ui/3-event-details/8-onscroll/2-updown-button/solution.view/index.html
  2-ui/3-event-details/8-onscroll/2-updown-button/source.view/index.html
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.view/index.html
  2-ui/3-event-details/8-onscroll/3-load-visible-img/source.view/index.html
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/3-event-details/8-onscroll/article.md
Labels: needs +1, review needed

#186 1-js/07-object-properties/01-property-descriptors
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: needs +1, review needed

#184 2-ui/2-events/01-introduction browser events(tasks only)
  2-ui/2-events/01-introduction-browser-events/01-hide-other/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/task.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.view/style.css
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/style.css
  2-ui/2-events/01-introduction-browser-events/07-carousel/task.md
Labels: needs +1, needs author response, review needed

#226 9-regular-expressions/13-regexp-multiline-mode
  9-regular-expressions/13-regexp-multiline-mode/article.md
Labels: needs +1

#219 2-ui/2-events/03-event-delegation
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/solution.view/index.html
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/source.view/index.html
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.view/index.html
  2-ui/2-events/03-event-delegation/2-sliding-tree/source.view/index.html
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/solution.view/index.html
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
  2-ui/2-events/03-event-delegation/bagua.view/index.html
Labels: needs +1, review needed

#228 1/03/03 comments fix lex111
  1-js/03-code-quality/03-comments/article.md
Labels: needs +1, review needed

#220 9-regular-expressions/11-regexp-alternation/
  9-regular-expressions/11-regexp-alternation/01-find-programming-language/solution.md
  9-regular-expressions/11-regexp-alternation/01-find-programming-language/task.md
  9-regular-expressions/11-regexp-alternation/02-find-matching-bbtags/solution.md
  9-regular-expressions/11-regexp-alternation/02-find-matching-bbtags/task.md
  9-regular-expressions/11-regexp-alternation/03-match-quoted-string/solution.md
  9-regular-expressions/11-regexp-alternation/03-match-quoted-string/task.md
  9-regular-expressions/11-regexp-alternation/04-match-exact-tag/solution.md
  9-regular-expressions/11-regexp-alternation/04-match-exact-tag/task.md
  9-regular-expressions/11-regexp-alternation/article.md
Labels: needs +1, review needed

#33 Перевод статьи 12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
Labels: needs +1, review needed

#131 1-js/06-advanced-functions/10-bind
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
  1-js/06-advanced-functions/10-bind/3-second-bind/solution.md
  1-js/06-advanced-functions/10-bind/3-second-bind/task.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
  1-js/06-advanced-functions/10-bind/article.md
Labels: needs +1, review needed

#159 Translate Promosify topic
  1-js/11-async/06-promisify/article.md
Labels: needs +1, review needed

#230 9-regular-expressions/10-regexp-backreferences
  9-regular-expressions/10-regexp-backreferences/article.md
Labels: needs +1, review needed

#231 6-data-storage/03-indexeddb
  6-data-storage/03-indexeddb/article.md
  6-data-storage/03-indexeddb/books.view/index.html
Labels: needs +1, review needed

#126 1-js/06-advanced-functions/11-currying-partials/article.md
  1-js/06-advanced-functions/11-currying-partials/1-ask-currying/solution.md
  1-js/06-advanced-functions/11-currying-partials/1-ask-currying/task.md
  1-js/06-advanced-functions/11-currying-partials/article.md
Labels: needs +1, review needed

#236 04 ninja code
  1-js/03-code-quality/04-ninja-code/article.md
Labels: review needed

#234 9-regular-expressions/14-regexp-lookahead-lookbehind
  9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
Labels: needs +1, review needed

#235 translation: keyboard events article + task + solution
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/solution.view/index.html
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/5-keyboard-events/article.md
  2-ui/3-event-details/5-keyboard-events/keyboard-dump.view/index.html
Labels: needs +1, review needed

#217 4 binary/01 arraybuffer binary arrays
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/solution.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/source.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/task.md
  4-binary/01-arraybuffer-binary-arrays/article.md
Labels: needs +1, review needed

#237 Перевести материал и задачи
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/source.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
  2-ui/1-document/07-modifying-document/11-append-to-list/solution.md
  2-ui/1-document/07-modifying-document/11-append-to-list/task.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.view/index.html
  2-ui/1-document/07-modifying-document/12-sort-table/source.view/index.html
  2-ui/1-document/07-modifying-document/12-sort-table/task.md
  2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
  2-ui/1-document/07-modifying-document/4-clear-elem/task.md
  2-ui/1-document/07-modifying-document/5-why-aaa/solution.md
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.view/index.html
  2-ui/1-document/07-modifying-document/6-create-list/task.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/source.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.view/index.html
  2-ui/1-document/07-modifying-document/8-tree-count/source.view/index.html
  2-ui/1-document/07-modifying-document/8-tree-count/task.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.view/index.html
  2-ui/1-document/07-modifying-document/9-calendar-table/source.view/index.html
  2-ui/1-document/07-modifying-document/9-calendar-table/task.md
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1, review needed

#212 9 regular expressions/15 regexp infinite backtracking problem
  9-regular-expressions/15-regexp-infinite-backtracking-problem/article.md
Labels: needs +1, review needed

#113 1-js/11-async/01-callbacks
  1-js/11-async/01-callbacks/01-animate-circle-callback/task.md
  1-js/11-async/01-callbacks/article.md
Labels: needs +1, review needed

#174 2 ui/1 document/08 styles and classes
  2-ui/1-document/08-styles-and-classes/2-create-notification/solution.view/index.html
  2-ui/1-document/08-styles-and-classes/2-create-notification/source.view/index.html
  2-ui/1-document/08-styles-and-classes/2-create-notification/task.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: needs +1, review needed

#88 Translated /1-js/06-advanced-functions/04-var
  1-js/06-advanced-functions/04-var/article.md
Labels: changes requested, needs +1

#243 1 js/06 advanced functions/04 var
  1-js/06-advanced-functions/04-var/article.md
Labels: needs +1, review needed

#229 1-js/06-advanced-functions/01-recursion
  1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
  1-js/06-advanced-functions/01-recursion/01-sum-to/task.md
  1-js/06-advanced-functions/01-recursion/02-factorial/solution.md
  1-js/06-advanced-functions/01-recursion/02-factorial/task.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/solution.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/task.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/task.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/task.md
  1-js/06-advanced-functions/01-recursion/article.md
Labels: changes requested, needs +1

#241 1 js/01 getting started/2 code editors
  1-js/01-getting-started/2-code-editors/article.md
Labels: needs +1

#192 Class basic syntax
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
Labels: needs +1, review needed

#199 2 ui/2 events/02 bubbling and capturing
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/02-bubbling-and-capturing/bubble-target.view/index.html
  2-ui/2-events/02-bubbling-and-capturing/bubble-target.view/script.js
Labels: needs +1, review needed

#244 symbols - translation: article
  1-js/04-object-basics/03-symbol/article.md
Labels: needs +1, review needed

#248 New: Make translate
  2-ui/1-document/10-size-and-scroll-window/article.md
Labels: needs +1, review needed

#249 1-js/07-object-properties/02-property-accessors
  1-js/07-object-properties/02-property-accessors/article.md
Labels: needs +1, review needed

#245 Сборка мусора
  1-js/04-object-basics/02-garbage-collection/article.md
Labels: needs +1, review needed

#251 2-ui/4-forms-controls
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1, review needed

#250 1-js/05-data-types/09-destructuring-assignment
  1-js/05-data-types/09-destructuring-assignment/1-destruct-user/task.md
  1-js/05-data-types/09-destructuring-assignment/6-max-salary/task.md
  1-js/05-data-types/09-destructuring-assignment/article.md
Labels: needs +1, review needed

#254 1 js/08 prototypes/02 function prototype
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/task.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: needs +1, review needed

#255 1 js/05 data types/08 keys values entries
  1-js/05-data-types/08-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/08-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/08-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/08-keys-values-entries/article.md
Labels: needs +1, review needed

#258 Замечена ошибка
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: needs +1

#68 1-js/04-object-basics/01-object/article.md translated
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/_js.view/solution.js
  1-js/04-object-basics/01-object/3-is-empty/_js.view/test.js
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/_js.view/source.js
  1-js/04-object-basics/01-object/8-multiply-numeric/_js.view/test.js
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/01-object/article.md
Labels: partially reviewed, work in progress

#256 5-network/06-url
  5-network/06-url/article.md
Labels: needs +1, review needed

#259 1 js/04 object basics/01 object
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/article.md
Labels: needs +1, review needed

#141 Translation of 1-js/06-advanced-functions/07-new-function
  1-js/06-advanced-functions/07-new-function/article.md
Labels: needs +1, review needed

#240 Перевод статьи Global object (1-js/06-advanced-functions/05-global-object/)
  1-js/06-advanced-functions/05-global-object/article.md
Labels: needs +1, review needed

#213 3-frames-and-windows/03-cross-window-communication
  3-frames-and-windows/03-cross-window-communication/article.md
  3-frames-and-windows/03-cross-window-communication/postmessage.view/iframe.html
  3-frames-and-windows/03-cross-window-communication/postmessage.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/sandboxed.html
Labels: needs +1, review needed

#132 1-js/09-classes/07-mixins
  1-js/09-classes/07-mixins/article.md
  1-js/09-classes/07-mixins/head.html
Labels: needs +1, review needed

#188 9-regular-expressions/07-regexp-quantifiers/article.md
  9-regular-expressions/07-regexp-quantifiers/1-find-text-manydots/solution.md
  9-regular-expressions/07-regexp-quantifiers/1-find-text-manydots/task.md
  9-regular-expressions/07-regexp-quantifiers/2-find-html-colors-6hex/solution.md
  9-regular-expressions/07-regexp-quantifiers/2-find-html-colors-6hex/task.md
  9-regular-expressions/07-regexp-quantifiers/article.md
Labels: needs +1, review needed

#260 1-js/02-first-steps/07-operators
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/1-increment-order/task.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/task.md
  1-js/02-first-steps/07-operators/article.md
Labels: needs +1, review needed

#183 1-js/03-code-quality/02-coding-style
  1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
  1-js/03-code-quality/02-coding-style/1-style-errors/task.md
  1-js/03-code-quality/02-coding-style/article.md
  1-js/03-code-quality/02-coding-style/code-style.png
  1-js/03-code-quality/02-coding-style/code-style@2x.png
Labels: needs +1, review needed

#266 5-network\08-websocket
  5-network/08-websocket/article.md
  5-network/08-websocket/chat.view/index.html
  5-network/08-websocket/chat.view/server.js
  5-network/08-websocket/demo.view/server.js
Labels: needs +1, review needed

#94 Translation of /1-js/03-code-quality/05-testing-mocha/
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/task.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/index.html
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
  1-js/03-code-quality/05-testing-mocha/index.html
  1-js/03-code-quality/05-testing-mocha/pow-1.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-1.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-2.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-2.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-3.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-3.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-4.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-4.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-full.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-full.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-min.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-min.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/test.js
Labels: needs +1, review needed

#246 1-js/04-object-basics/04-object-methods
  1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
  1-js/04-object-basics/04-object-methods/2-check-syntax/task.md
  1-js/04-object-basics/04-object-methods/3-why-this/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/task.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/_js.view/test.js
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/_js.view/test.js
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1, review needed

#262 Private protected properties methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1, review needed

#269 Остальные правки от pr 262
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1, review needed

#267 5-network/07-xmlhttprequest/: article + tasks + examples translated
  5-network/07-xmlhttprequest/article.md
  5-network/07-xmlhttprequest/example.view/index.html
  5-network/07-xmlhttprequest/example.view/server.js
  5-network/07-xmlhttprequest/hello.txt
  5-network/07-xmlhttprequest/phones-async.view/index.html
  5-network/07-xmlhttprequest/phones.view/index.html
  5-network/07-xmlhttprequest/phones.view/server.js
  5-network/07-xmlhttprequest/post.view/index.html
  5-network/07-xmlhttprequest/post.view/server.js
Labels: needs +1, review needed

#221 9-regular-expressions/09-regexp-groups
  9-regular-expressions/09-regexp-groups/1-find-webcolor-3-or-6/solution.md
  9-regular-expressions/09-regexp-groups/1-find-webcolor-3-or-6/task.md
  9-regular-expressions/09-regexp-groups/3-find-decimal-positive-numbers/solution.md
  9-regular-expressions/09-regexp-groups/3-find-decimal-positive-numbers/task.md
  9-regular-expressions/09-regexp-groups/4-find-decimal-numbers/solution.md
  9-regular-expressions/09-regexp-groups/4-find-decimal-numbers/task.md
  9-regular-expressions/09-regexp-groups/5-parse-expression/solution.md
  9-regular-expressions/09-regexp-groups/5-parse-expression/task.md
  9-regular-expressions/09-regexp-groups/article.md
Labels: needs +1, review needed

#222 8-web-components/7-shadow-dom-events
  8-web-components/7-shadow-dom-events/article.md
Labels: needs +1, review needed

#207 2-ui/1-document/09-size-and-scroll
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/ball-half/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.view/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/09-size-and-scroll/cssWidthScroll.view/index.html
  2-ui/1-document/09-size-and-scroll/metric.view/index.html
Labels: needs +1, review needed

#189 translation for data-types
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: needs +1, review needed
