Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2019-09, with the labels that each got.

#586 Update article.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#587 Update article.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: needs +1

#589 Update article.md
  1-js/06-advanced-functions/07-new-function/article.md
Labels: needs +1

#590 Update article.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1

#591 Update article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1

#592 Update article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#595 Ошибка в массиве дней недели: после "ПТ" (пятница) идет "ВС" (воскресенье)
  1-js/05-data-types/11-date/2-get-week-day/solution.md
Labels: needs +1

#585 Update solution.md
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
Labels: needs +1

#584 Update article.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1

#583 Update article.md
  2-ui/1-document/02-dom-nodes/article.md
Labels: needs +1

#599 Update article.md
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1

#598 Update article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: needs +1

#597 Update article.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1

#600 Update article.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: needs +1

#601 Update article.md
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1

#605 перевод
  1-js/10-error-handling/1-try-catch/article.md
Labels: needs +1

#608 Опечатка
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
Labels: needs +1

#606 Update article.md
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#604 Update article.md
  1-js/11-async/03-promise-chaining/article.md
Labels: needs +1

#603 Update article.md
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#593 Update article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#611 Fix comment error
  9-regular-expressions/05-regexp-multiline-mode/article.md
Labels: needs +1

#607 Update article.md
  1-js/05-data-types/12-json/article.md
Labels: needs +1

#561 Update article.md
  1-js/06-advanced-functions/07-new-function/article.md
Labels: needs +1

#509 Call apply правки
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1

#542 Update article.md
  20-css-for-js/2-css-units/article.md
Labels: needs +1

#602 Update article.md
  1-js/09-classes/07-mixins/article.md
Labels: needs +1

#616 Update article.md
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1

#614 Update article.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: needs +1

#596 Update article.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1, review needed

#610 Update article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#618 Пара опечаток
  20-css-for-js/6-css-center/article.md
Labels: needs +1

#621 Update article.md
  2-ui/1-document/11-coordinates/article.md
Labels: needs +1

#623 Update article.md
  2-ui/2-events/03-event-delegation/article.md
Labels: needs +1

#624 Исправление опечаток
  1-js/01-getting-started/3-code-editors/article.md
  1-js/02-first-steps/01-hello-world/article.md
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/07-operators/article.md
  1-js/02-first-steps/14-function-basics/article.md
  1-js/02-first-steps/15-function-expressions-arrows/article.md
  1-js/03-code-quality/04-ninja-code/article.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/08-weakmap-weakset/article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/05-promise-api/article.md
  1-js/11-async/08-async-await/article.md
  1-js/13-modules/01-modules-intro/article.md
  1-js/99-js-misc/01-proxy/article.md
  2-ui/1-document/01-browser-environment/article.md
  2-ui/1-document/08-styles-and-classes/article.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/3-event-details/5-keyboard-events/article.md
  2-ui/99-ui-misc/01-mutation-observer/article.md
  2-ui/99-ui-misc/02-selection-range/article.md
  20-css-for-js/10-box-sizing/article.md
  20-css-for-js/11-margin/article.md
  20-css-for-js/13-overflow/article.md
  20-css-for-js/17-css-sprite/article.md
  20-css-for-js/6-css-center/article.md
  4-binary/01-arraybuffer-binary-arrays/article.md
  5-network/04-fetch-abort/article.md
  5-network/06-fetch-api/article.md
  5-network/07-url/article.md
  5-network/10-long-polling/article.md
  5-network/11-websocket/article.md
  5-network/12-server-sent-events/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/03-indexeddb/article.md
  8-web-components/5-slots-composition/article.md
  8-web-components/6-shadow-dom-style/article.md
  9-regular-expressions/01-regexp-introduction/article.md
  9-regular-expressions/03-regexp-unicode/article.md
  9-regular-expressions/06-regexp-boundary/article.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
  9-regular-expressions/11-regexp-groups/article.md
  9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
  9-regular-expressions/16-regexp-sticky/article.md
  9-regular-expressions/17-regexp-methods/article.md
Labels: review needed

#626 Update article.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: review needed

#627 Update index.md
  2-ui/3-event-details/index.md
Labels: needs +1

#635 Update article.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#637 Revert "Update article.md"
  1-js/04-object-basics/04-object-methods/article.md
Labels: review needed

#641 Update article.md
  1-js/05-data-types/05-array-methods/article.md
Labels: review needed

#629 Update article.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1

#628 "Unreachable code" phrase translation
  1-js/13-modules/01-modules-intro/article.md
Labels: needs +1

#636 Update article.md
  1-js/06-advanced-functions/04-var/article.md
Labels: review needed

#639 Update article.md
  1-js/05-data-types/04-array/article.md
Labels: review needed

#642 fix regExp example
  9-regular-expressions/02-regexp-character-classes/article.md
Labels: needs +1

#644 change small mistake (not important, but i can't skip it)
  2-ui/1-document/08-styles-and-classes/article.md
Labels: needs +1

#640 error extends CoffeeMachine()
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#650 Update article.md
  1-js/05-data-types/12-json/article.md
Labels: review needed

#648 Update article.md
  1-js/05-data-types/11-date/article.md
Labels: review needed

#643 Update article.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: review needed

#663 Update article.md. Исправление опечатки
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: needs +1

#662 Update article.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: needs +1

#665 Update article.md
  20-css-for-js/6-css-center/article.md
Labels: needs +1

#666 Update article.md
  20-css-for-js/7-font-size-line-height/article.md
Labels: needs +1

#668 Update article.md
  9-regular-expressions/03-regexp-unicode/article.md
Labels: needs +1

#667 исправление опечаток
  9-regular-expressions/17-regexp-methods/article.md
Labels: needs +1

#672 Update article.md
  3-frames-and-windows/03-cross-window-communication/article.md
Labels: needs +1

#674 parseInt(str, base) в Итого
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#676 исправление опечаток
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1
