Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2019-08, with the labels that each got.

#327 Typo
  1-js/06-advanced-functions/06-function-object/article.md
Labels: review needed

#329 Fixed 08-async-await
  1-js/11-async/08-async-await/article.md
Labels: review needed

#335 Update article.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: review needed

#330 Update article.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: needs +1

#336 Ошибки перевода.
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1

#337 Update article.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#345 Update article.md
  1-js/13-modules/01-modules-intro/article.md
Labels: review needed

#346 Update article.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: review needed

#347 Event loop minor
  2-ui/99-ui-misc/03-event-loop/article.md
Labels: changes requested

#349 fix(DOM article): typo
  2-ui/1-document/02-dom-nodes/article.md
Labels: review needed

#343 fix: correct spelling of Curryng
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1

#350 Исправление опечаток
  1-js/01-getting-started/1-intro/article.md
Labels: review needed

#352 некоторые исправления
  1-js/11-async/07-microtask-queue/article.md
Labels: review needed

#351 Update article.md
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1

#354 prototype-inheritance
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
Labels: needs +1, review needed

#356 правки по mutation observer
  2-ui/99-ui-misc/01-mutation-observer/article.md
Labels: review needed

#358 Update article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: review needed

#359 Update article.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: review needed

#360 Update solution.md
  1-js/05-data-types/05-array-methods/1-camelcase/solution.md
Labels: review needed

#361 Update task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
Labels: needs +1

#368 Update article.md
  1-js/01-getting-started/1-intro/article.md
Labels: review needed

#369 Update article.md
  1-js/01-getting-started/4-devtools/article.md
Labels: needs +1

#370 Update article.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: review needed

#371 Update task.md
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
Labels: review needed

#372 Small typo in promise API description
  1-js/11-async/05-promise-api/article.md
Labels: review needed

#373 Update article.md
  1-js/02-first-steps/02-structure/article.md
Labels: review needed

#377 Update article.md
  1-js/02-first-steps/04-variables/article.md
Labels: review needed

#376 Update article.md
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#375 Update solution.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
Labels: review needed

#379 Update article.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: review needed

#378 Update article.md
  1-js/02-first-steps/05-types/article.md
Labels: review needed

#382 Update article.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: review needed

#384 Update article.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: review needed

#385 Update article.md
  1-js/02-first-steps/12-while-for/article.md
Labels: review needed

#386 Fix code snippet
  1-js/03-code-quality/05-testing-mocha/pow-full.view/index.html
Labels: review needed

#388 update article.md - задействовать несколько ядер
  2-ui/99-ui-misc/03-event-loop/article.md
Labels: needs +1

#392 Update article.md
  1-js/03-code-quality/02-coding-style/article.md
Labels: needs +1

#404 Update article.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#414 Update article.md
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: needs +1

#415 Update article.md
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1

#419 Исправляет "кодулях" на "модулях" и "создётся"
  1-js/13-modules/01-modules-intro/article.md
Labels: needs +1

#420 Исправляет опечатку
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: needs +1

#423 Перевод
  1-js/11-async/02-promise-basics/02-delay-promise/solution.md
Labels: needs +1

#413 Update article.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: needs +1

#430 fix(closure): typo
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1

#427 fix(rest-parameters-spread-operator): typo
  1-js/06-advanced-functions/02-rest-parameters-spread-operator/article.md
Labels: needs +1

#391 Update article.md
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: needs +1

#425 Update article.md
  9-regular-expressions/01-regexp-introduction/article.md
Labels: review needed

#424 Опечатка в примере в имени переменной
  9-regular-expressions/01-regexp-introduction/article.md
Labels: review needed

#417 Update article.md
  1-js/03-code-quality/06-polyfills/article.md
Labels: review needed

#416 Update article.md
  1-js/04-object-basics/03-symbol/article.md
Labels: review needed

#412 Update article.md
  1-js/05-data-types/07-map-set/article.md
Labels: review needed

#411 Update article.md
  1-js/05-data-types/05-array-methods/article.md
Labels: review needed

#409 Update article.md
  1-js/05-data-types/04-array/article.md
Labels: review needed

#407 Update article.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: review needed

#406 Update article.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: review needed

#432 Update article.md
  1-js/05-data-types/05-array-methods/article.md
Labels: needs +1

#422 Перевод
  1-js/11-async/02-promise-basics/03-animate-circle-promise/task.md
Labels: changes requested

#440 correct ending of a word
  2-ui/1-document/10-size-and-scroll-window/article.md
Labels: review needed

#439 Update article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#438 Исправление в слове один из операндов
  1-js/02-first-steps/07-operators/article.md
Labels: needs +1

#437 Classes
  1-js/09-classes/01-class/article.md
Labels: review needed

#436 Custom events
  2-ui/2-events/05-dispatch-events/article.md
Labels: review needed

#435 Вычитка
  1-js/04-object-basics/05-object-toprimitive/article.md
Labels: needs +1

#450 fix(property descriptors): typo
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: needs +1

#453 Update article.md
  3-frames-and-windows/01-popup-windows/article.md
Labels: needs +1

#452 Update article.md
  1-js/06-advanced-functions/01-recursion/article.md
Labels: needs +1

#454 Исправляет Collate на Collator
  1-js/99-js-misc/90-intl/1-collate-array-sort/task.md
Labels: needs +1

#400 Update article.md
  1-js/03-code-quality/03-comments/article.md
Labels: needs +1

#401 Update article.md
  1-js/04-object-basics/02-garbage-collection/article.md
Labels: needs +1

#441 Update article.md
  1-js/09-classes/06-instanceof/article.md
Labels: needs +1

#444 Update article.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#445 async minor
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/article.md
Labels: needs +1

#446 Вычитка. 7-animation/1-bezier
  7-animation/1-bezier-curve/article.md
Labels: needs +1

#461 Update article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: needs +1

#462 Typo fix for article.md
  8-web-components/6-shadow-dom-style/article.md
Labels: needs +1

#465 url encoding
  5-network/07-url/article.md
Labels: needs +1

#466 Update solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
Labels: needs +1

#467 typo
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#431 Update article.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1

#403 Update article.md
  1-js/04-object-basics/03-symbol/article.md
Labels: changes requested

#393 Update article.md
  1-js/03-code-quality/03-comments/article.md
Labels: needs +1

#443 async gen minor
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/head.html
Labels: needs +1

#470 Update article.md
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: needs +1

#468 fix(native prototypes): small fixes
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1

#473 Update article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
Labels: needs +1

#474 Update article.md
  2-ui/3-event-details/5-keyboard-events/article.md
Labels: needs +1

#471 Update article.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1

#478 Update article.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1

#476 Меняет removeChild на remove, как в примере
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
Labels: needs +1

#472 Update article.md
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1

#442 generators minor
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
  1-js/12-generators-iterators/1-generators/article.md
Labels: needs +1, review needed

#460 Вычитка. 7-animation/2-css-animations
  7-animation/2-css-animations/article.md
Labels: needs +1, review needed

#479 Update article.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#480 Вычитка. 7-animation/2-css-animations
  7-animation/2-css-animations/article.md
Labels: review needed

#455 Меняет var на let
  1-js/99-js-misc/90-intl/1-collate-array-sort/solution.md
Labels: review needed

#469 Ошибка в примере
  1-js/10-error-handling/1-try-catch/article.md
Labels: review needed

#475 Update article.md
  2-ui/99-ui-misc/01-mutation-observer/article.md
Labels: review needed

#463 Изменение подачи материала в строке 51
  1-js/06-advanced-functions/07-new-function/article.md
Labels: review needed

#451 Update article.md
  1-js/05-data-types/12-json/article.md
Labels: changes requested, needs +1

#449 Update article.md
  1-js/05-data-types/11-date/article.md
Labels: changes requested, needs +1

#410 Update article.md
  1-js/05-data-types/06-iterable/article.md
Labels: changes requested, needs +1

#395 Update article.md
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: changes requested, needs +1

#394 Update article.md
  1-js/03-code-quality/04-ninja-code/article.md
Labels: changes requested, needs +1

#380 Update article.md
  1-js/02-first-steps/03-strict-mode/article.md
Labels: needs +1

#493 Update article.md
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: needs +1

#491 Update article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#490 Update article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#487 fix(closure): fix typo
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1

#483 Несколько опечаток и грамматика
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#495 Update article.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1

#498 Update article.md
  1-js/99-js-misc/01-proxy/article.md
Labels: needs +1

#494 Update article.md
  1-js/06-advanced-functions/07-new-function/article.md
Labels: needs +1

#489 Update article.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#488 Добавляет перевод
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1

#486 Fix typo in variable name
  3-frames-and-windows/01-popup-windows/article.md
Labels: needs +1

#485 Пропущена буква
  1-js/02-first-steps/14-function-basics/article.md
Labels: needs +1

#505 Update article.md
  2-ui/1-document/02-dom-nodes/article.md
Labels: needs +1

#507 bind задача и мелкие правки
  1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
  1-js/06-advanced-functions/10-bind/article.md
Labels: needs +1, review needed

#503 стрелочные функции небольшие правки
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1

#511 Update article.md
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: needs +1

#510 Убирает лишниий знак
  6-data-storage/01-cookie/article.md
Labels: needs +1

#513 запятая
  4-binary/02-text-decoder/article.md
Labels: needs +1

#523 ccc => cc
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#515 Правки FileReader
  4-binary/04-file/article.md
Labels: needs +1, review needed

#525 Fix syntax error
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: needs +1

#529 Update article.md
  9-regular-expressions/02-regexp-methods/article.md
Labels: needs +1

#530 Исправляет опечатку
  9-regular-expressions/02-regexp-methods/article.md
Labels: needs +1

#533 Update article.md
  1-js/06-advanced-functions/05-global-object/article.md
Labels: needs +1

#538 Update article.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
Labels: needs +1

#547 fix typo
  5-network/05-fetch-crossorigin/article.md
Labels: needs +1

#526 Update article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: needs +1

#540 Update article.md
  2-ui/3-event-details/8-onscroll/article.md
Labels: needs +1

#539 fix typo in function-expressions-arrows arcticle
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: needs +1

#534 Update article.md
  1-js/05-data-types/06-iterable/article.md
Labels: needs +1

#531 Update article.md
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: needs +1

#551 Опечатка
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: needs +1

#554 fix typo in data-types-number article
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#555 Fix translation for a counter task
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
Labels: needs +1

#545 Update article.md
  1-js/06-advanced-functions/01-recursion/article.md
Labels: needs +1

#558 Update article.md
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#556 Fix typo in modules article
  1-js/13-modules/01-modules-intro/article.md
Labels: needs +1

#549 Update article.md
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: needs +1

#544 Update article.md
  1-js/06-advanced-functions/02-rest-parameters-spread-operator/article.md
Labels: needs +1

#541 Исправлены синтаксические ошибки
  5-network/03-fetch-progress/article.md
  5-network/04-fetch-abort/article.md
  5-network/05-fetch-crossorigin/article.md
Labels: needs +1

#560 need to translate
  1-js/04-object-basics/06-constructor-new/article.md
Labels: needs +1

#550 Update task.md
  1-js/02-first-steps/12-while-for/7-list-primes/task.md
Labels: needs +1

#524 fixed typo in article.md
  1-js/02-first-steps/12-while-for/article.md
Labels: review needed

#517 fixed typo выоа => вызова
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1

#566 changes in svg content
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
Labels: needs +1
