Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2019-05, with the labels that each got.

#122 обновление глоссария
  TRANSLATION.md
Labels: needs +1

#44 1-js/02-first-steps/03-strict-mode/
  1-js/02-first-steps/03-strict-mode/article.md
Labels: changes requested, needs +1

#45 Translate 1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/02-structure/article.md
Labels: needs +1, review needed

#49 9-regular-expressions_02-regexp-methods_article.md_ru
  9-regular-expressions/02-regexp-methods/article.md
Labels: needs +1, needs author response, work in progress

#72 1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/04-variables/article.md
Labels: needs +1, review needed, work in progress

#38 translate 01-debugging-chrome/article.md into Russian and update pict…
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/03-code-quality/01-debugging-chrome/chrome-open-sources.png
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-breakpoint.png
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-debugger-pause.png
Labels: needs +1, review needed

#106 translation 1-js/02-first-steps/14-function-basics
  1-js/02-first-steps/14-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/14-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/14-function-basics/2-rewrite-function-question-or/solution.md
  1-js/02-first-steps/14-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/14-function-basics/3-min/solution.md
  1-js/02-first-steps/14-function-basics/3-min/task.md
  1-js/02-first-steps/14-function-basics/4-pow/solution.md
  1-js/02-first-steps/14-function-basics/4-pow/task.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: needs +1, work in progress

#147 Revert "translation 1-js/02-first-steps/14-function-basics"
  1-js/02-first-steps/14-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/14-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/14-function-basics/2-rewrite-function-question-or/solution.md
  1-js/02-first-steps/14-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/14-function-basics/3-min/solution.md
  1-js/02-first-steps/14-function-basics/3-min/task.md
  1-js/02-first-steps/14-function-basics/4-pow/solution.md
  1-js/02-first-steps/14-function-basics/4-pow/task.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: review needed

#62 This resolves 3-frames-and-windows/01-popup-windows/ #21
  3-frames-and-windows/01-popup-windows/article.md
Labels: needs +1, review needed, work in progress

#76 4-binary / 03-blob
  4-binary/03-blob/article.md
Labels: needs +1, review needed, work in progress

#85 1-js/02-first-steps/06-type-conversions RU
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1

#82 fix(1-js/03-code-quality/06-polyfills): Перевести
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1, review needed

#93 translation of the /1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1, review needed

#115 Translate 1-js/02-first-steps/08-comparison
  1-js/02-first-steps/08-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/08-comparison/1-comparison-questions/task.md
  1-js/02-first-steps/08-comparison/article.md
Labels: needs +1, review needed, work in progress

#25 Translation 1-js/05-data-types/02-number
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/task.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/solution.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1, review needed

#79 1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/03-closure/1-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/1-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/2-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/2-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/3-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/3-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/4-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/4-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/6-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/6-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/7-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/8-make-army/solution.md
  1-js/06-advanced-functions/03-closure/8-make-army/task.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1, review needed

#96 1-js/05-data-types/11-json/* RU
  1-js/05-data-types/11-json/1-serialize-object/solution.md
  1-js/05-data-types/11-json/1-serialize-object/task.md
  1-js/05-data-types/11-json/2-serialize-event-circular/solution.md
  1-js/05-data-types/11-json/2-serialize-event-circular/task.md
  1-js/05-data-types/11-json/article.md
  1-js/05-data-types/index.md
Labels: needs +1, review needed

#102 Translated 1-js/02-first-steps/11-logical-operators/article.md
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/solution.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
  1-js/02-first-steps/11-logical-operators/8-if-question/task.md
  1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
  1-js/02-first-steps/11-logical-operators/9-check-login/task.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: needs +1, review needed

#124 fix(1-js/11-async/05-promise-api): Перевести главу и задачи
  1-js/11-async/05-promise-api/01-promise-errors-as-results/solution.md
  1-js/11-async/05-promise-api/01-promise-errors-as-results/task.md
  1-js/11-async/05-promise-api/02-promise-errors-as-results-2/task.md
  1-js/11-async/05-promise-api/article.md
Labels: needs +1, review needed

#23 translation of primitive-methods
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/task.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: needs +1, review needed

#121 Shadow DOM article translation
  8-web-components/3-shadow-dom/article.md
Labels: needs +1, review needed

#125 1-js/05-data-types/06-iterable
  1-js/05-data-types/06-iterable/article.md
Labels: needs +1, review needed

#134 1-js/09-classes/03-static-properties-methods/
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1, review needed

#92 09-alert-prompt-confirm
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: needs +1, review needed

#155 1-js/02-first-steps/04-variables/ Tasks
  1-js/02-first-steps/04-variables/1-hello-variables/solution.md
  1-js/02-first-steps/04-variables/1-hello-variables/task.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/2-declare-variables/task.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
Labels: needs +1, review needed

#127 1-js/04-object-basics/06-constructor-new
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/task.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/task.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/solution.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: needs +1, review needed

#40 #17: translate 8-web-components/1-webcomponents-intro/article.md
  8-web-components/1-webcomponents-intro/article.md
Labels: needs +1, review needed

#109 1 js/08 prototypes/03 native prototypes
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/solution.md
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/task.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/task.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1, review needed

#139 1 js/08 prototypes/04 prototype methods
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/task.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/task.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1, review needed

#140 1-js/13-modules/03-modules-dynamic-imports
  1-js/13-modules/03-modules-dynamic-imports/article.md
  1-js/13-modules/03-modules-dynamic-imports/say.view/index.html
  1-js/13-modules/03-modules-dynamic-imports/say.view/say.js
Labels: needs +1, review needed

#144 1 js/09 classes/06 instanceof
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
Labels: needs +1, review needed

#118 /1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1, review needed

#151 Template article translation
  8-web-components/4-template-element/article.md
Labels: needs +1, review needed

#158 translation of the /2-ui/4-forms-controls/4-forms-submit
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: needs +1, review needed

#160 Add 'character class' to the glossary
  TRANSLATION.md
Labels: needs +1

#78 9-regular-expressions/03-regexp-character-classes/article.md
  9-regular-expressions/03-regexp-character-classes/article.md
Labels: needs +1, review needed

#129 1-js/06-advanced-unctions/12-arrow-functions
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1, review needed

#70 1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#105 translation 1-js/02-first-steps/13-switch
  1-js/02-first-steps/13-switch/1-rewrite-switch-if-else/solution.md
  1-js/02-first-steps/13-switch/1-rewrite-switch-if-else/task.md
  1-js/02-first-steps/13-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/13-switch/2-rewrite-if-switch/task.md
  1-js/02-first-steps/13-switch/article.md
Labels: needs +1, review needed

#138 Перевод class inheritance
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/solution.md
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/task.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/task.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/solution.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/task.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: needs +1, review needed

#148 1-js/02-first-steps/14-function-basics
  1-js/02-first-steps/14-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/14-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/14-function-basics/2-rewrite-function-question-or/solution.md
  1-js/02-first-steps/14-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/14-function-basics/3-min/solution.md
  1-js/02-first-steps/14-function-basics/3-min/task.md
  1-js/02-first-steps/14-function-basics/4-pow/solution.md
  1-js/02-first-steps/14-function-basics/4-pow/task.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: needs +1, review needed

#169 2-ui/1-document/02-dom-nodes/
  2-ui/1-document/02-dom-nodes/article.md
  2-ui/1-document/02-dom-nodes/elks.html
Labels: needs +1, review needed

#182 fix typo in README.md
  README.md
Labels: ready to merge

#157 Translate 2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/01-introduction-browser-events/article.md
Labels: ready to merge, review needed

#161 7-animation/2-css-animation
  7-animation/2-css-animations/1-animate-logo-css/solution.md
  7-animation/2-css-animations/1-animate-logo-css/task.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/task.md
  7-animation/2-css-animations/3-animate-circle/task.md
  7-animation/2-css-animations/article.md
  7-animation/2-css-animations/boat.view/index.html
  7-animation/2-css-animations/digits.view/index.html
  7-animation/2-css-animations/step-end.view/index.html
  7-animation/2-css-animations/step.view/index.html
Labels: needs +1, review needed

#162 translate 9-regular-expressions/22-regexp-sticky
  9-regular-expressions/22-regexp-sticky/article.md
Labels: needs +1, review needed

#52 5-network/01-fetch-basics/article.md
  5-network/01-fetch-basics/article.md
Labels: needs +1, review needed

#163 9-regular-expressions/08-regexp-greedy-and-lazy/article.md
  9-regular-expressions/08-regexp-greedy-and-lazy/1-lazy-greedy/solution.md
  9-regular-expressions/08-regexp-greedy-and-lazy/1-lazy-greedy/task.md
  9-regular-expressions/08-regexp-greedy-and-lazy/3-find-html-comments/solution.md
  9-regular-expressions/08-regexp-greedy-and-lazy/3-find-html-comments/task.md
  9-regular-expressions/08-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/solution.md
  9-regular-expressions/08-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md
  9-regular-expressions/08-regexp-greedy-and-lazy/article.md
Labels: needs +1, review needed

#107 translation 1-js/04-object-basics/05-object-toprimitive
  1-js/04-object-basics/05-object-toprimitive/article.md
Labels: needs +1, review needed

#104 translation 1-js/02-first-steps/12-while-for
  1-js/02-first-steps/12-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/12-while-for/1-loop-last-value/task.md
  1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
  1-js/02-first-steps/12-while-for/2-which-value-while/task.md
  1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
  1-js/02-first-steps/12-while-for/3-which-value-for/task.md
  1-js/02-first-steps/12-while-for/4-for-even/solution.md
  1-js/02-first-steps/12-while-for/4-for-even/task.md
  1-js/02-first-steps/12-while-for/5-replace-for-while/task.md
  1-js/02-first-steps/12-while-for/6-repeat-until-correct/solution.md
  1-js/02-first-steps/12-while-for/6-repeat-until-correct/task.md
  1-js/02-first-steps/12-while-for/7-list-primes/solution.md
  1-js/02-first-steps/12-while-for/7-list-primes/task.md
  1-js/02-first-steps/12-while-for/article.md
Labels: needs +1, review needed

#114 translation 1-js/02-first-steps/15-function-expressions-arrows
  1-js/02-first-steps/15-function-expressions-arrows/1-rewrite-arrow/solution.md
  1-js/02-first-steps/15-function-expressions-arrows/1-rewrite-arrow/task.md
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: needs +1, review needed

#194 update current convention for backtick translation
  TRANSLATION.md
Labels: needs +1

#145 1-js/05-data-types/04-array/
  1-js/05-data-types/04-array/1-item-value/solution.md
  1-js/05-data-types/04-array/1-item-value/task.md
  1-js/05-data-types/04-array/10-maximal-subarray/solution.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/2-create-array/solution.md
  1-js/05-data-types/04-array/2-create-array/task.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/3-call-array-this/task.md
  1-js/05-data-types/04-array/5-array-input-sum/solution.md
  1-js/05-data-types/04-array/5-array-input-sum/task.md
  1-js/05-data-types/04-array/article.md
Labels: needs +1, review needed

#146 Translation 9-regular-expressions/04-regexp-escaping/article.md RU
  9-regular-expressions/04-regexp-escaping/article.md
Labels: needs +1, review needed

#150 Init 9-regular-expressions_05-regexp-character-sets-and-ranges-articl…
  9-regular-expressions/05-regexp-character-sets-and-ranges/article.md
Labels: needs +1, review needed

#164 1-js/13-modules/02-import-export/article.md
  1-js/13-modules/02-import-export/article.md
Labels: needs +1, review needed

#103 1-js/11-async/08-async-await translated
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/03-async-from-regular/solution.md
  1-js/11-async/08-async-await/03-async-from-regular/task.md
  1-js/11-async/08-async-await/article.md
Labels: needs +1

#120 /1-js/06-advanced-functions/09-call-apply-decorators
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/_js.view/source.js
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/solution.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1, review needed

#168 10-misc/12-mutation-observer (MutationOrbserver article translated)
  10-misc/12-mutation-observer/article.md
Labels: needs +1, ready to merge

#166 wip(1-js/13-modules/01-modules-intro): Перевести материал
  1-js/13-modules/01-modules-intro/article.md
  1-js/13-modules/01-modules-intro/scopes.view/hello.js
Labels: needs +1, review needed

#171 translation tasks and solutions for /1-js/02-first-steps/10-ifelse
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2/index.html
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/if_sign/index.html
  1-js/02-first-steps/10-ifelse/3-sign/solution.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/solution.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/solution.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
Labels: needs +1, review needed

#172 9-regular-expressions/21-regexp-unicode-properties
  9-regular-expressions/21-regexp-unicode-properties/article.md
Labels: needs +1, review needed

#136 1-js/06-advanced-functions/08-settimeout-setinterval
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/3-rewrite-settimeout/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/3-rewrite-settimeout/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: needs +1, review needed

#173 2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
Labels: needs +1, ready to merge

#175 1/09/05 (js/classes/extend-natives)
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1, review needed

#179 7-animation/3-js-animation
  7-animation/3-js-animation/1-animate-ball/solution.md
  7-animation/3-js-animation/1-animate-ball/task.md
  7-animation/3-js-animation/2-animate-ball-hops/solution.md
  7-animation/3-js-animation/2-animate-ball-hops/task.md
  7-animation/3-js-animation/article.md
  7-animation/3-js-animation/move-raf.view/index.html
  7-animation/3-js-animation/text.view/index.html
Labels: needs +1, review needed

#39 Translate 1-js/02-first-steps/01-hello-world/article.md #37
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1, review needed

#177 2-ui/1-document/04-searching-elements-dom (translation searching elements dom)
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: needs +1, review needed

#53 5-network/03-fetch-abort/article.md, translation
  5-network/03-fetch-abort/article.md
Labels: needs +1, review needed

#193 wip(1-js/11-async/04-promise-error-handling): Перевести главу
  1-js/11-async/04-promise-error-handling/01-error-async/solution.md
  1-js/11-async/04-promise-error-handling/01-error-async/task.md
  1-js/11-async/04-promise-error-handling/article.md
Labels: needs +1, review needed

#197 Fetch: Download progress
  5-network/02-fetch-progress/article.md
Labels: needs +1, review needed

#196 Data types / Array methods
  1-js/05-data-types/05-array-methods/1-camelcase/_js.view/solution.js
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/10-average-age/solution.md
  1-js/05-data-types/05-array-methods/10-average-age/task.md
  1-js/05-data-types/05-array-methods/11-array-unique/solution.md
  1-js/05-data-types/05-array-methods/11-array-unique/task.md
  1-js/05-data-types/05-array-methods/2-filter-range/_js.view/solution.js
  1-js/05-data-types/05-array-methods/2-filter-range/solution.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/_js.view/solution.js
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/solution.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  1-js/05-data-types/05-array-methods/4-sort-back/task.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/solution.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
  1-js/05-data-types/05-array-methods/6-array-get-names/solution.md
  1-js/05-data-types/05-array-methods/6-array-get-names/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/solution.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
  1-js/05-data-types/05-array-methods/7-map-objects/solution.md
  1-js/05-data-types/05-array-methods/7-map-objects/task.md
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
  1-js/05-data-types/05-array-methods/9-shuffle/task.md
  1-js/05-data-types/05-array-methods/article.md
Labels: needs +1

#202 1 js/10 error handling/1 try catch
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/1-try-catch/article.md
Labels: needs +1

#201 Ru 2 3 3 mousemove mouseover mouseout mouseenter mouseleave
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/solution.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/source.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/source.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/source.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation-2.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation-2.view/script.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseleave-table.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseleave.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseoverout-child.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseoverout-fast.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseoverout.view/index.html
Labels: needs +1, review needed

#153 Пополнение глоссария
  TRANSLATION.md
Labels: review needed

#215 File and FileReader
  4-binary/04-file/article.md
Labels: needs +1, review needed

#200 1-js/11-async/02-promise-basics
  1-js/11-async/02-promise-basics/01-re-resolve/solution.md
  1-js/11-async/02-promise-basics/01-re-resolve/task.md
  1-js/11-async/02-promise-basics/02-delay-promise/solution.md
  1-js/11-async/02-promise-basics/02-delay-promise/task.md
  1-js/11-async/02-promise-basics/03-animate-circle-promise/solution.view/index.html
  1-js/11-async/02-promise-basics/03-animate-circle-promise/task.md
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1, partially reviewed, review needed

#214 2-ui/1-document/05-basic-dom-node-properties/
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: needs +1, review needed
