Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2019-07, with the labels that each got.

#204 Resource loading: onload and onerror
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.view/index.html
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/source.view/index.html
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/task.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: needs +1, review needed

#257 /3-frames-and-windows/06-clickjacking
  3-frames-and-windows/06-clickjacking/article.md
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/facebook.html
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/index.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/facebook.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/index.html
  3-frames-and-windows/06-clickjacking/protector.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/index.html
Labels: needs +1, review needed

#274 Translate 1-js/05-data-types/10-date/article.md
  1-js/05-data-types/10-date/1-new-date/solution.md
  1-js/05-data-types/10-date/1-new-date/task.md
  1-js/05-data-types/10-date/2-get-week-day/_js.view/solution.js
  1-js/05-data-types/10-date/2-get-week-day/_js.view/test.js
  1-js/05-data-types/10-date/2-get-week-day/solution.md
  1-js/05-data-types/10-date/2-get-week-day/task.md
  1-js/05-data-types/10-date/3-weekday/_js.view/solution.js
  1-js/05-data-types/10-date/3-weekday/_js.view/test.js
  1-js/05-data-types/10-date/3-weekday/task.md
  1-js/05-data-types/10-date/4-get-date-ago/_js.view/test.js
  1-js/05-data-types/10-date/4-get-date-ago/solution.md
  1-js/05-data-types/10-date/4-get-date-ago/task.md
  1-js/05-data-types/10-date/5-last-day-of-month/_js.view/test.js
  1-js/05-data-types/10-date/5-last-day-of-month/solution.md
  1-js/05-data-types/10-date/5-last-day-of-month/task.md
  1-js/05-data-types/10-date/6-get-seconds-today/solution.md
  1-js/05-data-types/10-date/6-get-seconds-today/task.md
  1-js/05-data-types/10-date/7-get-seconds-to-tomorrow/solution.md
  1-js/05-data-types/10-date/7-get-seconds-to-tomorrow/task.md
  1-js/05-data-types/10-date/8-format-date-relative/_js.view/solution.js
  1-js/05-data-types/10-date/8-format-date-relative/_js.view/test.js
  1-js/05-data-types/10-date/8-format-date-relative/solution.md
  1-js/05-data-types/10-date/8-format-date-relative/task.md
  1-js/05-data-types/10-date/article.md
Labels: needs +1, review needed

#242 2-ui/4-forms-controls/3-events-change-input
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/solution.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/source.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
  2-ui/4-forms-controls/3-events-change-input/article.md
Labels: needs +1, review needed

#277 2 ui/1 document/01 browser environment
  2-ui/1-document/01-browser-environment/article.md
Labels: needs +1, review needed

#276 9 regular expressions/20 regexp unicode
  9-regular-expressions/20-regexp-unicode/article.md
Labels: needs +1, review needed

#279 9-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1
  9-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1/solution.md
  9-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1/task.md
Labels: needs +1

#278 9-regular-expressions/03-regexp-character-classes/1-find-time-hh-mm
  9-regular-expressions/03-regexp-character-classes/1-find-time-hh-mm/solution.md
  9-regular-expressions/03-regexp-character-classes/1-find-time-hh-mm/task.md
Labels: needs +1, review needed

#280 9-regular-expressions/05-regexp-character-sets-and-ranges/2-find-time-2-formats
  9-regular-expressions/05-regexp-character-sets-and-ranges/2-find-time-2-formats/solution.md
  9-regular-expressions/05-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
Labels: needs +1, review needed

#284 1-js/04-object-basics/index.md #60
  1-js/04-object-basics/index.md
Labels: needs +1

#285 1-js/08-prototypes/index.md #60
  1-js/08-prototypes/index.md
Labels: needs +1

#283 1-js/03-code-quality/index.md #60
  1-js/03-code-quality/index.md
Labels: needs +1

#286 1-js/09-classes/index.md #60
  1-js/09-classes/index.md
Labels: needs +1

#287 1 js/06 advanced functions/index.md
  1-js/06-advanced-functions/index.md
Labels: needs +1

#261 5-network/05-fetch-api
  5-network/06-fetch-api/article.md
Labels: needs +1, partially reviewed, review needed

#289 1 js/99 js misc/02 eval
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
  1-js/99-js-misc/02-eval/article.md
Labels: review needed

#282 2 ui/4 forms controls/4 forms submit
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/source.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/index.md
Labels: review needed

#290 5 network/09 resume upload
  5-network/09-resume-upload/article.md
  5-network/09-resume-upload/upload-resume.view/index.html
  5-network/09-resume-upload/upload-resume.view/server.js
  5-network/09-resume-upload/upload-resume.view/uploader.js
Labels: review needed

#293 Задание из главы Fetch
  5-network/01-fetch/01-fetch-users/_js.view/source.js
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
Labels: review needed

#281 1 js/01 getting started/2 manuals specifications
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: review needed

#295 5 network/02 formdata
  5-network/02-formdata/article.md
  5-network/02-formdata/post.view/server.js
Labels: review needed

#296 2-ui/99-ui-misc/03-event-loop
  2-ui/99-ui-misc/03-event-loop/article.md
Labels: needs +1, review needed

#297 1 js/11 async/03 promise chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/03-promise-chaining/getMessage.js
  1-js/11-async/03-promise-chaining/head.html
Labels: review needed

#270 2 ui/2 events/05 dispatch events
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1, review needed

#305 Minor improvements to the article
  1-js/02-first-steps/12-while-for/article.md
Labels: review needed

#291 Long polling
  5-network/10-long-polling/article.md
  5-network/10-long-polling/longpoll.view/browser.js
  5-network/10-long-polling/longpoll.view/index.html
  5-network/10-long-polling/longpoll.view/server.js
Labels: needs +1, review needed

#300 Patch 1
  1-js/03-code-quality/03-comments/article.md
Labels: review needed

#302 1-js/12-generators-iterators/1-generators
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/solution.md
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
  1-js/12-generators-iterators/1-generators/article.md
Labels: needs +1, review needed

#299 1 js/99 js misc/01 proxy
  1-js/99-js-misc/01-proxy/01-error-nonexisting/solution.md
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/02-array-negative/solution.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/03-observable/solution.md
  1-js/99-js-misc/01-proxy/03-observable/task.md
  1-js/99-js-misc/01-proxy/article.md
Labels: review needed

#301 RU 06-data-storage/02-localstorage
  6-data-storage/02-localstorage/1-form-autosave/solution.view/index.html
  6-data-storage/02-localstorage/1-form-autosave/task.md
  6-data-storage/02-localstorage/article.md
Labels: needs +1, review needed

#308 Update article.md
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/source.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
Labels: needs +1, review needed

#265 Dragndrop
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.css
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.css
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.js
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
Labels: needs +1, review needed

#263 Add translation for chapter Map, Set, WeakMap and WeakSet
  1-js/05-data-types/07-map-set-weakmap-weakset/01-array-unique-map/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/02-filter-anagrams/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/04-recipients-read/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/04-recipients-read/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/05-recipients-when-read/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/05-recipients-when-read/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/article.md
Labels: needs +1, review needed

#307 Server Sent Events
  5-network/12-server-sent-events/article.md
  5-network/12-server-sent-events/eventsource.view/index.html
  5-network/12-server-sent-events/eventsource.view/server.js
Labels: needs +1, review needed

#310 2 ui/1 document/11 coordinates
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/source.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/2-position-at/solution.md
  2-ui/1-document/11-coordinates/2-position-at/solution.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/source.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/task.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.view/index.html
  2-ui/1-document/11-coordinates/3-position-at-absolute/task.md
  2-ui/1-document/11-coordinates/4-position-inside-absolute/task.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/1-document/11-coordinates/head.html
Labels: review needed

#272 Strings
  1-js/05-data-types/03-string/1-ucfirst/_js.view/test.js
  1-js/05-data-types/03-string/1-ucfirst/solution.md
  1-js/05-data-types/03-string/1-ucfirst/task.md
  1-js/05-data-types/03-string/2-check-spam/_js.view/test.js
  1-js/05-data-types/03-string/2-check-spam/solution.md
  1-js/05-data-types/03-string/2-check-spam/task.md
  1-js/05-data-types/03-string/3-truncate/_js.view/test.js
  1-js/05-data-types/03-string/3-truncate/solution.md
  1-js/05-data-types/03-string/3-truncate/task.md
  1-js/05-data-types/03-string/4-extract-currency/_js.view/test.js
  1-js/05-data-types/03-string/4-extract-currency/task.md
  1-js/05-data-types/03-string/article.md
Labels: needs +1, review needed

#314 translation index.html
  8-web-components/5-slots-composition/menu.view/index.html
Labels: review needed

#312 Maps update
  1-js/05-data-types/08-weakmap-weakset/article.md
Labels: review needed

#303 Custom elements
  8-web-components/2-custom-elements/1-live-timer/solution.md
  8-web-components/2-custom-elements/1-live-timer/solution.view/live-timer.js
  8-web-components/2-custom-elements/1-live-timer/source.view/index.html
  8-web-components/2-custom-elements/1-live-timer/source.view/live-timer.js
  8-web-components/2-custom-elements/1-live-timer/task.md
  8-web-components/2-custom-elements/article.md
Labels: needs +1, review needed

#313 translation Shadow DOM slots, composition
  8-web-components/5-slots-composition/article.md
Labels: review needed

#315 Shadow dom style
  8-web-components/6-shadow-dom-style/article.md
Labels: needs +1, review needed

#317 Selection and Range
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: needs +1, review needed

#318 6-data-storage/01-cookie
  6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/cookie.js
Labels: review needed
