Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2020-02, with the labels that each got.

#833 Fix typo
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: needs +1

#834 Update article.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: needs +1

#835 Delete a confusing comment
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: review needed

#776 fix setCookie (fails when options.expires is not set or is not a Date)
  6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/cookie.js
Labels: needs +1, review needed

#838 Update article.md
  5-network/05-fetch-crossorigin/article.md
Labels: review needed

#839 typo correction
  2-ui/2-events/04-default-browser-action/article.md
Labels: needs +1

#813 Add translation of BigInt chapter
  1-js/02-first-steps/05-types/article.md
  1-js/05-data-types/02-number/article.md
  1-js/99-js-misc/05-bigint/article.md
Labels: needs +1, review needed

#843 Improve JS quiz
  quiz/quiz-js.yml
Labels: review needed

#842 Improve DOM quiz
  quiz/quiz-dom.yml
Labels: review needed

#845 Мелкий штрих с расстановкой слов
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#846 fix markdown in article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
Labels: needs +1

#849 fix bigInt md link
  1-js/02-first-steps/05-types/article.md
  1-js/99-js-misc/05-bigint/article.md
Labels: needs +1

#851 fix(closure/tasks/filter-through-function): межу -> между
  1-js/06-advanced-functions/03-closure/6-filter-through-function/task.md
Labels: needs +1

#857 Update article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: needs +1

#859 Функционал -> Функциональность
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/06-advanced-functions/06-function-object/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/08-prototypes/03-native-prototypes/article.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/09-classes/07-mixins/article.md
  1-js/13-modules/01-modules-intro/article.md
  1-js/13-modules/02-import-export/article.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/04-bitwise-operators/article.md
  2-ui/1-document/01-browser-environment/article.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/source.view/hoverIntent.js
  2-ui/99-ui-misc/01-mutation-observer/article.md
  5-network/08-xmlhttprequest/article.md
  8-web-components/5-slots-composition/article.md
  99-archive/006-iterator/article.md
  99-archive/012-set-map/article.md
  99-archive/013-promise/article.md
  99-archive/024-testing/article.md
  99-archive/033-closures-usage/2-stringbuffer/task.md
  99-archive/039-decorators/article.md
  99-archive/041-exception/article.md
  99-archive/053-dom-console/article.md
  99-archive/065-websockets/article.md
  99-archive/077-custom-events/article.md
  99-archive/083-ajax-iframe/article.md
  99-archive/090-closures-module/article.md
  99-archive/093-functional-inheritance/article.md
  99-archive/098-drag-and-drop-plus/article.md
  99-archive/110-fiddler/article.md
  TRANSLATION.md
Labels: needs +1

#860 Basic DOM node properties text fixed
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: needs +1

#861 Update "Якоря: начало строки ^ и конец $"
  9-regular-expressions/04-regexp-anchors/article.md
Labels: needs +1

#862 Misprint correction
  2-ui/2-events/03-event-delegation/bagua.view/index.html
Labels: needs +1

#867 Исправление шаблонных строк в примерах кода
  1-js/99-js-misc/05-bigint/article.md
Labels: needs +1
