Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2022-02, with the labels that each got.

#1487 fix: правка приоритета оператора "??"
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: review needed

#1223 Replace a non-existent words
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs author response, review needed

#1437 Update article.md
  2-ui/5-loading/02-script-async-defer/article.md
Labels: needs +1

#1489 update images.yml
  images.yml
Labels: review needed

#1491 Лишняя запятая перед «и»
  1-js/02-first-steps/16-function-expressions/article.md
Labels: review needed

#1494 fix: добавил пропущенное объявление переменной в главе "Циклы while и for"
  1-js/02-first-steps/13-while-for/article.md
Labels: review needed

#1493 Update article.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: needs +1

#1495 Update article.md
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#951 (pass == '') have to return wrong pass msg
  1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
Labels: needs author response, review needed

#1499 Ошибка в перечислении таблицы
  1-js/02-first-steps/13-while-for/article.md
Labels: review needed

#1500 Ошибка в переводе со ссылкой на проблему #1376
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: review needed

#1503 Исправление приоритета операторов
  1-js/02-first-steps/08-operators/article.md
Labels: needs +1

#1507 Отсутствующая точка с запятой
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: review needed

#1517 Полагаю что я добавил возможность запускать код
  1-js/02-first-steps/13-while-for/article.md
Labels: review needed

#1508 Мне кажется так будет более правильно
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1

#1519 a small change to match the original
  1-js/02-first-steps/15-function-basics/article.md
Labels: review needed
