Repository javascript-tutorial/ru.javascript.info, pull requests merged in 2022-03, with the labels that each got.

#1513 added the missing translation
  1-js/02-first-steps/15-function-basics/article.md
Labels: review needed

#1532 minor grammar fix and link update
  1-js/13-modules/02-import-export/article.md
Labels: review needed

#1537 fix indents
  1-js/03-code-quality/03-comments/article.md
Labels: review needed

#1528 some fixes
  1-js/03-code-quality/02-coding-style/article.md
Labels: review needed

#1534 fix term name
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: review needed

#1541 Fix typo issue #1527
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#1551 add comma
  8-web-components/3-shadow-dom/article.md
Labels: needs +1

#1560 Выполнить перевод до конца "Hello" "Привет"
  1-js/02-first-steps/15-function-basics/article.md
Labels: needs +1

#1505 Update solution.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/solution.md
Labels: review needed

#1562 just placed "ё" letters
  1-js/05-data-types/02-number/article.md
  2-ui/1-document/08-styles-and-classes/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  5-network/11-websocket/article.md
  99-archive/124-books/article.md
Labels: needs +1

#1558 add changes according to commit from english edition
  1-js/09-classes/03-static-properties-methods/article.md
Labels: review needed

#1524 Small adjustments to match the original
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: review needed

#1555 Обновил статью
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: changes requested

#1525 some fixes
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: review needed

#1563 Update article.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: needs +1

#1511 Update article.md
  6-data-storage/03-indexeddb/article.md
Labels: needs +1

#1515 Отсутсвие заголовков
  5-network/05-fetch-crossorigin/article.md
Labels: needs +1
